### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
Travis CI is down so let's replace it with a GitHub Action...
Output: https://github.com/cclauss/python-gphoto2/actions

https://packages.ubuntu.com/search?keywords=gphoto2
https://packages.ubuntu.com/search?keywords=swig

### CODE REVIEW

**Comment by jim-easterbrook** [comment]
You obviously know more about GitHub actions than I do, but I don't see how this replaces Travis. I set up the Travis stuff to test compiling the SWIG generated code with different C compilers (that I don't have on my local machine). This Python lint stuff just appears to be checking the example programs, unless I've missed something.

**Comment by cclauss** [comment]
I added the Travis CI commands and they all seem to pass.  This Action is linting the entire repo so it should catch issues in any Python code throughout the repo.

**Comment by jim-easterbrook** [comment]
Thanks. Let me know when you've finished tweaking your changes and I'll merge it in.

**Comment by cclauss** [comment]
I am finished tweaking.  I was trying to figure out what `pytest --doctest-modules .` is not finding `gphoto2` but you can probably figure that out better than I can.

**Pull request merged**
